### ISSUE TITLE
Add custom data

### ISSUE THREAD

**Issue by versh23** [DamienHarper/auditor-bundle#113]
Hello, is it possible to add custom data to audit entry ?
for example uid http request .

can we create a json field to audit table and do dispatch event before insert payload to table ?

**Comment by DamienHarper** [comment]
Hi @versh23, thanks for your feedback. It seems a good idea, I need some time to think about it.

**Comment by gam6itko** [comment]
It issue similar to #147

**Comment by DamienHarper** [comment]
> It issue similar to #147

#147 would benefit from this event system but the goal here is to add custom data to audit entries, not filtering them.

**Comment by Thomas-Philippot** [comment]
Hi ! Any news about it ?
I was just about to find a way to add custom data to my audit entries.

**Comment by dvdknaap** [comment]
I'm looking for the same thing.

I know you can change the values with (https://github.com/DamienHarper/auditor-bundle/blob/3.x/src/DoctrineAuditBundle/Event/AuditSubscriber.php) but you can't change the fields.

@DamienHarper is it possible to make the 'AuditEntry' entity modifiable in the yaml config file ?
In this case we can modify the fields and are in full control

```yaml
dh_doctrine_audit:
    AuditEntry: App\Entity\AuditEntry
```

**Comment by DamienHarper** [comment]
@versh23 This is now possible in `master` branch. You can now alter the payload borrowed by an audit event from an even subscriber.
