### ISSUE TITLE
Possibility to add custom action

### ISSUE THREAD

**Issue by garak** [DamienHarper/auditor-bundle#145]
I need to audit a custom action, e.g. an action that is not the typical "insert", "update", etc.
So, what I tried first is to define my service, inject `AuditManager` in it and do something similar to `insert` method (or `update` method, etc.).
It works, the only issue is that I had to copy/paste the entire `audit` method, since it's private.

My proposal is to increase visibility of such method, to protected or to public.

With public method, my simple solution would work without any further effort.
With protected method, I could decorate the service (but such solution maybe should go with an interface to implement, something like `AuditManagerInterface`)

**Comment by DamienHarper** [comment]
@garak the bundle is aimed to keep track of changes happening at database level and the viewer is not designed to display audit entries outside of this scope. 
I have to think about it a bit more

**Comment by Tersoal** [comment]
@DamienHarper I would like to register when I make bulk import because I need to do in raw SQL. It would be an example of @garak said.

I have to explore audit manager to achieve it.

**Comment by garak** [comment]
Well, IMHO the viewer is too much for this bundle and it should be on a separate repository (I'm not using it).
Anyway, my proposal is just about making the process more flexible

**Comment by rcapile** [comment]
Hi @DamienHarper, have you had the chance to look at it? I imagined something like

```php
public function customAction(
        EntityManagerInterface $em,
        $entity,
        string $action,
        string $message,
        array $context = []
    ) {
        /** @var ClassMetadata $meta */
        $meta = $em->getClassMetadata(DoctrineHelper::getRealClassName($entity));
        $this->audit(
            [
                'action' => 'custom',
                'blame' => $this->getHelper()->blame(),
                'diff' => array_merge(['_custom' => $action, '_message' => $message], $context),
                'table' => $meta->getTableName(),
                'schema' => $meta->getSchemaName(),
                'id' => $this->getHelper()->id($em, $entity),
                'transaction_hash' => \sha1(\uniqid('tid', true)),
                'discriminator' => $this->getDiscriminator($entity, $meta->inheritanceType),
                'entity' => $meta->getName(),
            ]
        );
    }
```
and used as 

```php
 public function audit(AuditManager $auditManager, EntityManagerInterface $entityManager)
    {
        $user = $this->getUser();
        $auditManager->customAction(
            $entityManager,
            $user,
            'login',
            'User logged in',
            ['something' => 'is', 'expected' => 'here', 'for' => 'context']
        );

        $auditManager->customAction($entityManager, $user, 'login', 'User logged in without context');
    }
```

With some changes at `entry.html.twig`, `helpers/bootstrap.html.twig` and  `helpers/helper.html.twig` the view could be

![image](https://user-images.githubusercontent.com/189857/78615304-7b029780-7847-11ea-8572-2900c6ff2558.png)

I believe It would break nothing since it's a new functionality. I can make I pull request if you like

**Comment by DamienHarper** [comment]
@garak This is now possible in `master` branch. You can now alter the payload borrowed by an audit event from an even subscriber.
