### ISSUE TITLE
Get audit log for a specific user

### ISSUE THREAD

**Issue by n3o77** [DamienHarper/auditor-bundle#164]
I'm trying to retrieve all changes from a specific user for specific or all audited entities. I was looking into adding more filters to the AuditReader but endet up changing a lot of code, so not sure if that makes sense and wanted your feedback on this @DamienHarper .

If you're interested in something like that i think it would make sense to pass a general filter object instead which would also include the transaction hash. This would allow to add more filters in the future without too many api changes.

As always, thank you for the work on this bundle.

**Comment by DamienHarper** [comment]
@n3o77 Sorry for the delay, your filter object looks like a good idea. May you submit a PR? I'd be glad to review it ;)

**Comment by n3o77** [comment]
No worries. Sure I can work on a PR in the next few weeks. Thanks for the feedback.

**Comment by DamienHarper** [comment]
@n3o77 @McAnix has made a PR (#172) adding the ability to get audits within a date range. 
As long as you plan to make a PR regarding filters, it might be nice to support the same filtering feature (date range).

**Comment by DamienHarper** [comment]
@n3o77 any progress on this?

**Comment by gisostallenberg** [comment]
@DamienHarper How about splitting `getAudits` in two public methods `prepare`, resulting in a querybuilder and `execute` (or `read` or `get`) requiring said querybuilder and resulting in the array returned by `getAudits` normaly. This allows alter the querybuilder to ones own needs.
`getAuditsByDate` could be calling prepare and execute and add the dates to the querybuilder in between.

**Comment by DamienHarper** [comment]
@gisostallenberg that's currently being done in the rewrite that will be pushed on the repo in a quite near future ;)

**Comment by gisostallenberg** [comment]
I see. That's nice. Thanks in advance.

**Comment by gisostallenberg** [comment]
btw, another way would be to allow a (or multiple) filter classes of some kind to be set. This would be a class that implements the interface requiring a method `apply` accepting the query builder
```php
interface AuditReaderFilter {
   public function apply(\Doctrine\DBAL\Query\QueryBuilder $queryBuilder);
}
```
This allows for a reader that works the same over and over again and can be compiled in the service container.

**Comment by gisostallenberg** [comment]
@DamienHarper can I help to create a filter system like that? All internal filters currently applied could also be added this way and having a way to remove them might allow people to read the audits in any way they want.
Maybe 'filter' is not a good term, because of the existing `filterBy` which narrows types.

**Comment by DamienHarper** [comment]
@gisostallenberg First of all, sorry for the delay. You should be able to do such filtering using the new `Query` object and applying a filter on the user, cf. https://damienharper.github.io/auditor-docs/docs/auditor-bundle/usage/querying.html#query

**Note**: This is only available on the `master` branch as of now.
