### ISSUE TITLE
Update schema 

### ISSUE THREAD

**Issue by ndiouga25** [DamienHarper/auditor-bundle#176]
Hello ,i  using symfony 3.4 and i want to integrate your audit bundle .But when i finsih to install the composer and i want to upgrade my schema sql i have alaways this issue [OK] Nothing to update.   
this is my config.yml    
      default_connection: central
        connections:
            default:
            central:
            instance:
      

    orm:
        default_entity_manager: central
        entity_managers:
            default:               
            central:
            instance:
               
        

    
dh_doctrine_audit:
    table_prefix: 'audit_'
    table_suffix: ''
    timezone: 'Europe/London'
    enabled: true

**Comment by DamienHarper** [comment]
Hi @ndiouga25, thanks for the report. I suspect your issue is related to #157. I have to investigate a bit more.

**Comment by ndiouga25** [comment]
Hi , did the same think . But i cannot update my schema .

**Comment by DamienHarper** [comment]
@ndiouga25 do you want all of your entities managed by all your entity managers to be audited or do you only want to audit entities managed by a specific entity manager?

If you only want to audit entities managed by a single entity manager, did you try to specify it in the `dh_doctrine_audit.yaml` file?

```yaml
dh_doctrine_audit:
    storage_entity_manager: doctrine.orm.your_custom_entity_manager
```

(see [doc](https://github.com/DamienHarper/DoctrineAuditBundle/blob/master/doc/20-general-configuration.md#storage-configuration))

**Comment by ndiouga25** [comment]
i want to audit only some of my entries not all all . My symfony is 3.4 and
i want configure my audit bundle in confih.yml .
When i tape this command  bin/console audit:schema:update i always have
this screen shot .

Le lun. 9 mars 2020 à 14:18, Damien Harper <notifications@github.com> a
écrit :

**Comment by DamienHarper** [comment]
@ndiouga25 Sorry for the delay, this should be fixed in `master` branch. I close this issue but feel free to reopen it if needed.
