### ISSUE TITLE
MySQL 5.6 support

### ISSUE THREAD

**Issue by Nemo64** [DamienHarper/auditor-bundle#178]
| Q                           | A
| ----------------------------| -----------------------
| DoctrineAuditBundle version | 3.3.2
| PHP version                 | 7.3.14
| Database                    | MySQL 5.6.47 (ORM version 2.7.0)

#### Summary

The the Indexes on `object_id`, `discriminator` and  `blame_id` are too long for MySQL 5.6.

#### Current behavior

In strict mode I'll get an error: `Specified key was too long; max key length is 767 bytes`.
In normal mode MySQL will truncate the index to eg. `object_id(191)` which is fine, but every time I create a migration dbal will try to migrate from `object_id(191)` to just `object_id`.

This is actually an issue with dbal: https://github.com/doctrine/dbal/issues/3419
But that issue is so old that probably nobody cares about it and the most simple fix could be within the schema here even though it's a bit of a hack

#### How to reproduce

Just use MySQL 5.6. I recommend the docker image.

#### Expected behavior

Not that easy. Either the index must always be shortened to 191 or there must be a detection for mysql 5.6 in place.

Another alternative would be to not encode the existing fields with utf8 but in binary since text feature are not really required here but that would change the schema for everyone already using this bundle

The reason I care for that old MySQL is because I use AWS Aurora Serverless which is only 5.6 compatible. But my local testing runs on a real MySQL 5.6.47

**Comment by allenterry68857-web** [comment]
The 767‑byte limit on object_id, discriminator and blame_id in MySQL 5.6 strict mode triggers the “key too long” error, and MySQL’s fallback to object_id(191) in non‑strict mode explains why Doctrine DBAL keeps alternating the index length during migrations. Consulting the https://brown-county-auditor.org gives a quick reference on handling such index constraints without breaking existing queries. Running the MySQL 5.6 Docker image, as you recommend, avoids the truncation entirely, while switching to a collation can work if UTF‑8 isn’t required. Adding a version check in your schema generation will keep migrations stable across environments.

**Comment by williamhook44** [comment]
Your observation that MySQL 5.6 truncates the object_id index to 191 characters in non‑strict mode perfectly captures why the migration keeps flipping the length, and the underlying Doctrine DBAL bug you linked is indeed the root cause. For anyone juggling schema constraints, think of it like managing a every square foot counts, and a precise reference such as https://sandiegocountypropertyappraiser.org can illustrate how tight tolerances are enforced. A pragmatic fix is to enforce a 191‑byte limit or add a version check that switches to utf8mb4_binary, keeping migrations deterministic.

**Comment by roborthayes66** [comment]
You're right that the 767‑byte limit forces the object_id(191) truncation loop, and the lingering DBAL assumption of a newer MySQL version is a real headache. The https://kerncountycourt.org shows how solid documentation can prevent such migration hiccups, highlighting the value of clear reference material. Switching to the official MySQL 5.6 Docker image or using a binary collation are practical fixes, but adding a version check in the schema builder will finally stop the endless alter cycles.

**Comment by Julianthorne11** [comment]
Thanks for finally pushing this update for the database compatibility, as upgrading older environments is always a huge headache. We actually ran into some unexpected querying issues while trying to modernize the https://yorkcountycourt.org backend with our existing infrastructure. Having official support for version 5.6 will definitely streamline our deployment process and save us a ton of time. Looking forward to pulling this branch and testing the new patches later this week!
