### ISSUE TITLE
@Gedmo\Translatable and DoctrineAuditBundle

### ISSUE THREAD

**Issue by grekpg** [DamienHarper/auditor-bundle#184]
I'm using @Gedmo\Translatable
I see that auditBundle create entry but don't store in with locale was change 

this is diff
{"title": {"new": "test EN 123", "old": test 1 EN"}}

**Comment by DamienHarper** [comment]
@grekpg Sorry for the delay, I suppose that the locale used for translation is stored/defined wether in the translation listener or as an unmapped property in your entities, thus we have no way to guess its value. 

Though, using `master` branch you can create your own `EventSubscriber` that subscribe to audit events and then alter the `diffs` property of the event payload to add your own data such as the current translation locale.

I close this issue as this is won't be included in `auditor` any time soon. Feel free to reopen it if needed. 
I'd also be glad to help you if needed.
