### ISSUE TITLE
Symfony 5.1 deprecated role ROLE_PREVIOUS_ADMIN

### ISSUE THREAD

**Issue by massimilianobraglia** [DamienHarper/auditor-bundle#206]
Hey there, 
thank you for this bundle!

```Since symfony/security-core 5.1: The ROLE_PREVIOUS_ADMIN role is deprecated and will be removed in version 6.0, use the IS_IMPERSONATOR attribute instead.```

Any plan to support this?

**Comment by DamienHarper** [comment]
@massimilianobraglia Sorry for the delay, this is fixed in `3.x` and `master` branches

**Comment by massimilianobraglia** [comment]
@DamienHarper thank you! A new release is coming then?

**Comment by DamienHarper** [comment]
@massimilianobraglia yep

**Comment by DamienHarper** [comment]
@massimilianobraglia `3.4.2` has been released, `4.0` will come quite shortly

**Comment by massimilianobraglia** [comment]
Thank you, @DamienHarper!
