### ISSUE TITLE
SQL syntax error when creating audit log entries

### ISSUE THREAD

**Issue by joshgh** [DamienHarper/auditor-bundle#208]
| Q                           | A
| ----------------------------| -----------------------
| `auditor-bundle` version    | 3.4.1
| PHP version                 | 7.3.15
| Database                    | MySQL 5.7

#### Summary

Unable to create audit entries

#### Current behavior

When updating or saving any entity that is auditable the following error occurs

An exception occurred while executing 'INSERT INTO lesson_audit (type, object_id, discriminator, transaction_hash, diffs, blame_id, blame_user, blame_user_fqdn, blame_user_firewall, ip, created_at) VALUES (:type, :object_id, :discriminator, :transaction_hash, :diffs, :blame_id, :blame_user, :blame_user_fqdn, :blame_user_firewall, :ip, :created_at)':

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':type, :object_id, :discriminator, :transaction_hash, :diffs, :blame_id, :blame_' at line 1

#### How to reproduce

Install auditorbundle, mark an entity as auditable, and make any changes to that entity

#### Expected behavior

Change to entity is correctly persisted and audit entry is created

**Comment by joshgh** [comment]
I also tried downgrading doctrine-audit-bundle to each version down to 3.3.0 and had the same problematic behavior.

**Comment by joshgh** [comment]
Ok, it appears that the issue is the mysqli driver does not support named parameters in prepared statements. So DH\DoctrineAuditBundle\Event\AuditSubscriber::onAuditEvent creates problems. I did not see any note that mysqli is unsupported, so just something in the docs to this effect would be helpful.

**Comment by DamienHarper** [comment]
@joshgh Sorry for the delay, it should be fine on the `master` branch.

**Comment by DamienHarper** [comment]
@joshgh Did you update your schema to create audit table in the first place?
Try running `bin/console audit:schema:update --force` first.

**Comment by DamienHarper** [comment]
@joshgh Any news on this issue? I close it for now, feel free to reopen it if needed.
