### ISSUE TITLE
Version support

### ISSUE THREAD

**Issue by kirya-dev** [DamienHarper/auditor-bundle#209]
What is version that compatible with original entity audit bundle ?

In my case me need save original database structure for `*_audit` tables.

**Comment by DamienHarper** [comment]
Hi @kirya-dev, I'm not sure to understand your question, the latest stable release (fully operational) is `3.4.1`, you can get it with the following command: `composer require damienharper/auditor-bundle`

Documentation is available here: https://github.com/DamienHarper/auditor-bundle/blob/3.x/doc/00-index.md

**Comment by kirya-dev** [comment]
original bundle save changes as new record and insert changed value as new record in audit..
But **DamienHarper / auditor-bundle** save in json changed data - its take more data on disk and need convert old structure to new

**Comment by DamienHarper** [comment]
@kirya-dev I'm confused, this bundle has always (since the beginning) used `json_encode` to save diffs in audit tables.
