### ISSUE TITLE
Is it possible to track one-to-many relation without versionning target entity ?

### ISSUE THREAD

**Issue by samy** [DamienHarper/auditor-bundle#210]
Hi !
I have a small question : I have an Entity which can have be related to many othier Entity2 (a one-to-many relation)

I plan to track changes on Entity (and to track changes on the list of Entity2 instances related to my Entity)

Is it possible without versionning also Entity2 ?

**Comment by DamienHarper** [comment]
@samy First of all, sorry for the delay. If I'm not wrong with your "setup", at the schema level, entity2 table will have a foreign key coming from entity1 table. 

In such a scenario, entity1 table has no link with entity2 so if you enable auditing of entity1 table and disable auditing of entity2 table, operations on entity1 will be audited but operations on entity2 won't. 

As long as associations and dissociations are done thanks to the foreign key in entity2 table and that entity2 table is not audited, associations and dissociations won't be audited as well.
