### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by ramil8090** [DamienHarper/auditor-bundle#212]
Hi,

there is no documentation for the bundle. Any links in README.md lead to 404 error page.

**Comment by Herz3h** [comment]
For some reasons v4 doesn't have the doc folder, you can read https://github.com/DamienHarper/auditor-bundle/tree/3.x for version 3 if needed.

**Comment by dgfmdrv** [comment]
I don't know but I found this repo with docs, maybe the author has move folder doc to their own repo
https://github.com/DamienHarper/auditor-docs
