### ISSUE TITLE
Get original Entity class name from AuditEntity

### ISSUE THREAD

**Issue by vincentdieltiens** [DamienHarper/auditor-bundle#213]
Hi,

Is there a way to get the original entity class name from an `AuditEntry` object ?

I'm using FOSRestBundle + JMSSerializerBundle for an API. That API allows to get the history of a resource but I want to display the related entities as well (not just the primary key). For that purpose, I have a specific JMS Serializer Handler to serialize entries as I want.

So when serializing an `AuditEntry`, I need to get the original entity class so that I can use metadata to get relations informations and fetch the related entities.

Thanks

**Comment by DamienHarper** [comment]
@vincentdieltiens First of all, sorry for the delay. It is not possible to get the original entity from an audit entry.
