### ISSUE TITLE
Diffs of removed entities not tracked in other entities

### ISSUE THREAD

**Issue by chripu** [DamienHarper/auditor-bundle#215]
Hi @DamienHarper,

first of all thanks for the great bundle!

I have a "problem" and could need an advise.

Let's assume I have two entities.

```php
class User {
    /**
     * @Id
     * @Column(type="integer")
     * @GeneratedValue
     */
    private $id;

    /**
     * @ManyToOne(targetEntity="Address", mappedBy="users")
     */
    private $address;

    // getter + setters
}
```

```php
class Address {
    /**
     * @Id
     * @Column(type="integer")
     * @GeneratedValue
     */
    private $id;

    /**
     * @OneToMany(targetEntity="User", mappedBy="address")
     */
    private $users;

    // getter + setters
}
```

**Both are audited.**

Let's further assume I have an `Address` and want to delete it. The address is used in an `User`. Before the removal I will set the Address to NULL, so no foreign key constrait is violated on deletion.

```php
$user->setAddress(NULL);
$em->remove($address);
$em->flush();
```

I would expect to have **two audit entries** in this transaction:
- a remove audit entry for `Address#1`.
- an update audit entry for`User#1` with diff:

Property | Old | New
-------- | --- | ---
address | Address#1 | NULL

**But the audit entry for User#1 is missing.**

---

**I know why it happens, but not how I can prevent it.**

Doctrine does the following [on remove](https://www.doctrine-project.org/projects/doctrine-orm/en/2.7/reference/working-with-objects.html#removing-entities):
> After an entity has been removed its in-memory state is the same as before the removal, except for generated identifiers.

So in `$auditHelper->diff(...)` the `$this->summarize($em, $old);` will return `NULL`, because `$auditHelper->id(..)` will return NULL for the primary key property, because the generated identifier has been reset by doctrine in the remove process.

With the condition `if ($o !== $n) { ... }` (`$o` and `$n` both evaluating to `NULL`) no audit diff is registered, even if there was a change.

What can I do to have the audit entry for the nullifying of the address?

**Comment by DamienHarper** [comment]
@chripu First of all, sorry for the delay. I don't have any real solution for your issue as it is related to Doctrine internals. 
I close this issue, feel free to comment / reopen if necessary.
