### ISSUE TITLE
Column names for multiple self-referencing tables

### ISSUE THREAD

**Issue by Jurek-Raben** [DamienHarper/auditor-bundle#217]
We use a table with multiple reference id onto itself. These references all have different column names. Sadly you can't see which column name it is in the audit log at all. So it is not possible to see which self-reference actually is meant.

My suggestion would be then to include the column name into the log entry, or introduce an additional @AuditColumnName annotation or so.

**Comment by DamienHarper** [comment]
@Jurek-Raben Im' not sure to fully understand what you expect here, could you please elaborate on that feature request? I'd like to better understand how you would use that. Can you please provide an example/use case?

**Comment by Jurek-Raben** [comment]
This request can be deleted, it was related to https://github.com/DamienHarper/auditor-bundle/issues/220
