### ISSUE TITLE
Include 'isOwningSide' into diff column

### ISSUE THREAD

**Issue by Jurek-Raben** [DamienHarper/auditor-bundle#220]
It would be very helpful, if your bundle was including the $mapping['isOwningSide'] into the diff table column, since with this additional info, you could track which side was affected in a bidirectional (self referencing) many-to-many relation.

e.g. in the AuditManager in associateOrDissociate() and similar.

**Comment by DamienHarper** [comment]
@Jurek-Raben Sorry for the delay, could you please elaborate on that feature request? I can add that info to relevant entries but I'd like to better understand how you would use that. Can you please provide an example/use case?

**Comment by Jurek-Raben** [comment]
Hi,

thanks for your concern!
I mean a change in the AuditManager class, in the method associateOrDissociate(), e.g. like:

```
private function associateOrDissociate(string $type, EntityManagerInterface $em, $source, $target, array $mapping, string $transactionHash): void
    {
        /** @var ClassMetadata $meta */
        $meta = $em->getClassMetadata(DoctrineHelper::getRealClassName($source));
        $data = [
            'action' => $type,
            'blame' => $this->helper->blame(),
            'diff' => [
                'source' => $this->helper->summarize($em, $source),
                'target' => $this->helper->summarize($em, $target),
                'isOwningSide' => $mapping['isOwningSide'],
            ],
            'table' => $meta->getTableName(),
            'schema' => $meta->getSchemaName(),
            'id' => $this->helper->id($em, $source),
            'transaction_hash' => $transactionHash,
            'discriminator' => $this->getDiscriminator($source, $meta->inheritanceType),
            'entity' => $meta->getName(),
        ];

        if (isset($mapping['joinTable']['name'])) {
            $data['diff']['table'] = $mapping['joinTable']['name'];
        }

        $this->audit($data);
    }
```

Here is an use case example: Let's say you have an entity A and you have two self referencing properties P1 and P2, which are relations to the same entity A, like:
```
class EntityA {
...
    /**
     * @var Collection
     *
     * @ORM\ManyToMany(targetEntity="EntityA", inversedBy="anchestors")
     * @ORM\JoinTable(name="entitya_chain")
     */
    private $anchestors;

    /**
     * @var Collection
     *
     * @ORM\ManyToMany(targetEntity="EntityA", mappedBy="followers")
     * @ORM\JoinTable(name="entitya_chain")
     */
    private $followers;
 ...
}

```

In the above example, it is impossible to know now without the information "isOwningSide" whether the anchestors or the followers were changed. So the owningSide info is a lot helpful.

**Comment by DamienHarper** [comment]
@Jurek-Raben This is fixed in `master` branch. Feel free to reopen if needed.

**Comment by Jurek-Raben** [comment]
Thanks!
