### ISSUE TITLE
How to view audit log in browser

### ISSUE THREAD

**Issue by ivyasyeshugo** [DamienHarper/auditor-bundle#227]
Hello 

I am using audit log version 3.0 for my project, I had successfully configured it, and the logs are working fine,
but my question is how can i view  log entries in the browser, when I visit the `/audit` it says authentication required, my project had some security firewall, but I had removed the audit route from the security although i am not able to see log entries in browse

Also if i want to restrict log history to a particular user i.e( only the admin can see the log history) then how can i achieve it.

Quick response will really help me a lot

Thanks

**Comment by DamienHarper** [comment]
Hi @ivyasyeshugo! Could you please post your `security.yaml` file?

**Comment by ivyasyeshugo** [comment]
below is current code of my security.yaml file
`security:
    encoders:
        App\Entity\User:
            algorithm: argon2i

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: name

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_docs:
            anonymous: ~
            pattern: ^/$
        applicant:
          anonymous: ~
          pattern: ^/applicant/
        graphql_playground:
            anonymous: ~
            pattern: ^/graphql/graphql_playground$
        login:
            anonymous: ~
            pattern: ^/(login$|register)
            stateless: true
        password:
            anonymous: ~
            pattern: ^/password/(forgot|reset)$
            stateless: true
        api:
            pattern: ^/
            stateless: true
            guard:
                authenticators:
                  - App\Security\TokenAuthenticator
                  - App\Security\FirebaseAuthenticator
                entry_point: App\Security\TokenAuthenticator`
                
 below is the code I tried to put in this file, to view the logs in the browser
 `audit:
            anonymous: ~
            pattern: ^/audit`

**Comment by DamienHarper** [comment]
@ivyasyeshugo where did you place the audit section in this file? Remember that order is important, the first firewall that matches your request is used (see https://symfony.com/doc/current/security.html#a-authentication-firewalls)
> Only one firewall is active on each request: Symfony uses the pattern key to find the first match (you can also match by host or other things).

**Comment by DamienHarper** [comment]
@ivyasyeshugo you should also think about migrating to v4.x of this bundle ;)

**Comment by ivyasyeshugo** [comment]
I don't think the order is important in my case, because I had tried to place everywhere in firewall before after in the middle etc.. but not works, 
is there something I am missing?

For migrating to v4.x I can't right now because I have some issues with my Symfony version (4.4.16 )

**Comment by DamienHarper** [comment]
> I don't think the order is important in my case, because I had tried to place everywhere in firewall before after in the middle etc.. but not works

Well, I'm pretty sure order is important here as stated in Symfony doc. 

You should place your `audit` firewall somewhere **before** the  `api` one because this one catches any path starting with `/` (so it would catch paths like `/audit` and `/audit/...`)

Also, how did you defined routes to the audit viewer? can you post your `routes.yaml` file?

Finally, did you clear the cache each time you changed these files?

> For migrating to v4.x I can't right now because I have some issues with my Symfony version (4.4.16 )

I'm not sure to understand properly: you're currently using Symfony 4.4.16 and have some troubles so you don't want to update the audit bundle until you fixed your troubles with 4.4.16?
Just to remember, the v4.x of the bundle is compatible with all supported Symfony versions (3.4, 4.4 and 5.x).

**Comment by ivyasyeshugo** [comment]
Now I had fix the route issue, but it comes up with another below error 

`This page contains the following errors:
error on line 234 at column 12: Opening and ending tag mismatch: link line 0 and head
Below is a rendering of the page up to the first error.
DoctrineAuditBundle .timeline-centered { position: relative; margin-bottom: 30px; font-size: 0.9rem; clear: both; } .timeline-centered:before, .timeline-centered:after { content: " "; display: table; } .timeline-centered:after { clear: both; } .timeline-centered:before, .timeline-centered:after { content: " "; display: table; } .timeline-centered:after { clear: both; } .timeline-centered:before { content: ''; position: absolute; display: block; width: 4px; background: #f5f5f6; left: 10%; top: 20px; bottom: 20px; margin-left: -4px; } .timeline-centered .timeline-entry { position: relative; width: 90%; float: right; margin-bottom: 15px; clear: both; } .timeline-centered .timeline-entry:before, .timeline-centered .timeline-entry:after { content: " "; display: table; } .timeline-centered .timeline-entry:after { clear: both; } .timeline-centered .timeline-entry:before, .timeline-centered .timeline-entry:after { content: " "; display: table; } .timeline-centered .timeline-entry:after { clear: both; } .timeline-centered .time`

**Comment by DamienHarper** [comment]
I'm sorry but I can't help here without more information.
What did you fix exactly? How do you get this error? Did you modified/override templates? Etc

**Comment by ivyasyeshugo** [comment]
i am accessing `/audit` and in security.yaml I am using `/audit/` so that additional `/` was the fix.

Also had not changed anything in code just I view the route and it gave me this error

**Comment by DamienHarper** [comment]
Could you post a screenshot of the full error please? The stack trace would also help ;)

**Comment by ivyasyeshugo** [comment]
![Uploading aduit-error.png…]()

**Comment by ivyasyeshugo** [comment]
![aduit-error](https://user-images.githubusercontent.com/72447420/102889752-370cfc80-4481-11eb-80b1-f7477abff617.png)

**Comment by DamienHarper** [comment]
Looks like your layout is broken but I don't know where. Check your twig files 🤔

**Comment by DamienHarper** [comment]
@ivyasyeshugo did you solve your problem?

**Comment by ivyasyeshugo** [comment]
No not yet, nothing from my code base, so not able get whats the actual problem

**Comment by DamienHarper** [comment]
@ivyasyeshugo The error mentions an opening / closing tag mismatch, check the links and head tags of your layout

**Comment by DamienHarper** [comment]
@ivyasyeshugo Try adding a `/` before the `>` on line 7 of `src/DoctrineAuditBundle/Resources/views/layout.html.twig` of the bundle (in the vendors) and let me know if it fixes your issue

**Comment by ivyasyeshugo** [comment]
it gaves me this
![image](https://user-images.githubusercontent.com/72447420/102984981-6df01a80-4534-11eb-9a39-54d632ad224e.png)

**Comment by DamienHarper** [comment]
@ivyasyeshugo Ok that's when you review source in your browser but does it fix the issue? Is the audit inventory displayed properly?

**Comment by ivyasyeshugo** [comment]
No, that's not the view source it is actually showing this when visiting the audit page.

**Comment by DamienHarper** [comment]
@ivyasyeshugo the problem is outside of the bundle, it looks like the bad content type is used in the response hence displaying the source

**Comment by DamienHarper** [comment]
@ivyasyeshugo did you solve your problem?

**Comment by ivyasyeshugo** [comment]
@DamienHarper Not at all, still we are looking for it if you have any idea about that why its showing XML instead of HTML, any configuration file or something else needs to change then it will help me, I had used the API platform of symfony

**Comment by DamienHarper** [comment]
@ivyasyeshugo it looks like something changes the response content type, maybe another installed bundle or a custom event listener for example

**Comment by ivyasyeshugo** [comment]
@DamienHarper  as we have now changes in our requirement, so we don't need to do this as of now,
Thanks for your extensive support, I really appreciate it.
