### ISSUE TITLE
Track read actions

### ISSUE THREAD

**Issue by Seb33300** [DamienHarper/auditor-bundle#229]
Hello,

Is there any way using this bundle to track `read` actions?
I mean, track when a user access to the content of an entity.

If this is not possible to do automatically, is there any way to manually create and save custom audit log using this bundle?

Thank you

**Comment by DamienHarper** [comment]
@Seb33300 I'm not sure to fully understand what you mean by _"access to the content of an entity"_
There are several ways to access the content of an entity:
- using properties (eg. `$entity->property`)
- using accessors (eg. `$entity->getProperty()`

In both cases, no event if fired so we are not able to log this to an audit log.

It could only be possible if  "accessing the content of an entity" was centralized in a dedicated helper function/method (eg. `MyEntityContentAccessor::getContent('property')`) in which you could trigger the audit process or if you trigger the audit process in every getter.

Feel free to reopen this issue if needed.
