### ISSUE TITLE
Please change required php version for php8

### ISSUE THREAD

**Issue by grekpg** [DamienHarper/auditor-bundle#230]
This package requires php ^8 but your PHP version (7.4.11) does not satisfy that requirement.

**Comment by DamienHarper** [comment]
@grekpg as of now, the `composer.json` file requires `"php": ">=7.2",` so it should not trigger the error you mention. Could you please elaborate?

**Comment by DamienHarper** [comment]
@grekpg any news about this?

**Comment by DamienHarper** [comment]
@grekpg No feedback so I close this issue, feel free to reopen if needed.
