### ISSUE TITLE
Database problem

### ISSUE THREAD

**Issue by Pollares01** [DamienHarper/auditor-bundle#231]
After running the command `composer install damienharper/auditor-bundle`, the configuration files have been created.

But no change in my database!
`bin/console doctrine:migrations:diff` displays that no changes were detected.

How can I add the audit tables to my database? Do I have to create these tables myself?

**Comment by DamienHarper** [comment]
Hi @Pollares01, did you configure which entities have to be audited either thanks to the [configuration file](https://damienharper.github.io/auditor-docs/docs/auditor-bundle/configuration/auditing.html#audited-entities-and-properties) or by using [annotations](https://damienharper.github.io/auditor-docs/docs/auditor-bundle/configuration/auditing.html#annotations)?

**Comment by Pollares01** [comment]
Hello @DamienHarper 

Yes I did it.
![image](https://user-images.githubusercontent.com/55586343/104563525-0b2d0300-564a-11eb-9464-5e11d12142e3.png)

**Comment by DamienHarper** [comment]
@Pollares01 Could you please post your compiled container as a gist for example?
(it should be located in a path similar to `var/cache/XXX/ContainerYYY/App_KernelProdContainer.php` where `XXX` should match the environment such as `dev` or `prod` and `YYY` is some random chars)

**Comment by Pollares01** [comment]
Yes sure.

https://pastebin.com/HxUr8b4q

**Comment by DamienHarper** [comment]
@Pollares01 well it's quite weird and I can't reproduce the issue. 
Could you share me a your project (if not to sensible) so that I can reproduce the issue?

**Comment by DamienHarper** [comment]
@Pollares01 could you try again using `master` branch?

**Comment by Pollares01** [comment]
Sorry I didn't answer earlier, but my development guidelines have changed, so I don't have to use your library anymore, I removed it from my project. Maybe I would use it later! 

Thank you for your help

**Comment by DamienHarper** [comment]
@Pollares01 thanks for the feedback
