### ISSUE TITLE
Symfony 3.4 Support broken with ViewerEventSubscriber in 4.0

### ISSUE THREAD

**Issue by Alarich** [DamienHarper/auditor-bundle#237]
| Q                           | A
| ----------------------------| -----------------------
| `auditor-bundle` version    | 4.0.3
| PHP version                 | 7.3.24
| Database                    | MySQL
| Symfony                     | 3.4.47

#### Summary

[ViewerEventSubscriber](https://github.com/DamienHarper/auditor-bundle/blob/1d9c5ee434a53982185ca2922d9d34977d4ca66d/src/Event/ViewerEventSubscriber.php) is using ControllerEvent, which was [introduced in Symfony 4.3](https://github.com/DamienHarper/auditor-bundle/blob/1d9c5ee434a53982185ca2922d9d34977d4ca66d/src/Event/ViewerEventSubscriber.php), thus making minimum compatibility Symfony >= 4.3 instead of Symfony >= 3.4. 

#### Current behavior

TypeError is thrown due to mismatching input for the onKernelController event:
```
Type error: Argument 1 passed to DH\AuditorBundle\Event\ViewerEventSubscriber::onKernelController() must be an instance of Symfony\Component\HttpKernel\Event\ControllerEvent, instance of Symfony\Component\HttpKernel\Event\FilterControllerEvent given, called in /...path.../vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php on line 115
```

#### How to reproduce

Enable 4.x on a Symfony 3.4 project.

#### Expected behavior

Receive no error and be able to accommodate Symfony 3.4 - 4.2. As everything else seems to function correctly.

#### Potential solution

This could be solved by simply typehinting a KernelEvent and then checking if getController exists. Or perhaps there's a better method.

**Comment by DamienHarper** [comment]
@Alarich This should be fixed in `master` new, can you confirm?

**Comment by Alarich** [comment]
Yes, this is exactly what I did in my override.
Thanks @DamienHarper :)
