### ISSUE TITLE
AuditReader->getAudits by array of ids

### ISSUE THREAD

**Issue by Viktor-Bredihin** [DamienHarper/auditor-bundle#244]
AuditReader->getAudits - I can get only all records or one record by id, I wish to be able to pass array of ids
The problem is that most of methods are private and I can expand this class

**Comment by DamienHarper** [comment]
@Viktor-Bredihin As long as you mention `AuditReader`, I suppose you are using version `3.x` of the bundle. If so, you can't pass multiple values to `AuditReader::getAudit()` method. 

I strongly suggest you to upgrade to version `4.x` of this bundle to get more control and filters so you can achieve what you expect. Upgrading is easy and documented [here](https://damienharper.github.io/auditor-docs/docs/auditor-bundle/upgrading.html)

**Comment by Viktor-Bredihin** [comment]
@DamienHarper 
thank you very much, it works great
