### ISSUE TITLE
Doctrine Migrations not managing audit table.

### ISSUE THREAD

**Issue by mathieu-gilloots** [DamienHarper/auditor-bundle#245]
| Q                           | A
| ----------------------------| -----------------------
| `auditor-bundle` version    | 4.1.0
| PHP version                 | 7.4.15
| Database                    | MySQL

#### Summary

When I'm installing the bundle, "_audit" table are autogenerated and not managed by doctrineMigations.
Doctrine Migrations, want's to remove the table when the bundle created it.

#### Current behavior
"audit" table are auto-created when I try to run `doc:mig:diff`.
The audit table are not on my generated migration but It's auto created.
When I run `doc:mig:diff` again, the new migration wants to remove _audit table because it's not managed by doctrine_migrations.

#### How to reproduce
Install the Bundle, configure one entity with @Auditable() & @Ignore on some fields,
run `doc:mig:diff`, _audit table are created in datable, but not generated in the migration file.
When I run `doc:mig:diff` it's wants to remove the auto created audit table.

#### Expected behavior
The audit table are not auto created in database.
When I run `doc:mig:diff` It's add on the up() function the SQL to create the _audit table.

config.yml :
```
dh_auditor:
    enabled: true
    providers:
        doctrine:
            table_prefix: null
            table_suffix: '_audit'
```

Class: 
```
use DH\Auditor\Provider\Doctrine\Auditing\Annotation\Auditable;
use DH\Auditor\Provider\Doctrine\Auditing\Annotation\Ignore;

/**
 * @Auditable()
 */
class MyClass {
/**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @Ignore()
     */
    private $id;

    /**
     * @ORM\ManyToOne(...)
     * @ORM\JoinColumn(...)
     * @Ignore()
     */
    private $variableToIgnore;

 /**
     * @ORM\ManyToOne(...)
     * @ORM\JoinColumn(...)
     */
    private $variableToAudit;
} 
```

First run of `doc:mig:diff` : table myclass_audit created on database, but no "CREATE TABLE myclass_table" on the migration files
Second run of `doc:mig:diff` : on the up() function: 
`DROP table myclass_audit`

Thanks

**Comment by DamienHarper** [comment]
@mathieu-gilloots thanks for the report, I'll have a look asap

**Comment by Metabor** [comment]
Have the same issue after running composer update.
Before there was no such issue.

**Comment by adrav** [comment]
have the same issue.
Pls fix ASAP.

**Comment by DamienHarper** [comment]
This should be fixed in `master`. 
Other fixes regarding `audit:schema:update` command should come quite shortly.

**Comment by DamienHarper** [comment]
Everything should be fine on `master`. I close this issue for now, feel free to reopen if needed.
