### ISSUE TITLE
Doctrine migrations wants to drop tables

### ISSUE THREAD

**Issue by denis1994** [DamienHarper/auditor-bundle#249]
| Q                           | A
| ----------------------------| -----------------------
| `auditor-bundle` version    | 4.10
| PHP version                 | 7.4.4
| Database                    | MySQL

#### Summary

I upgraded from the old DoctrineAuditBundle to the new auditor-bundle with this guide: https://damienharper.github.io/auditor-docs/docs/auditor-bundle/upgrading.html#upgrading-from-a-previous-version.
The upgraded process worked fine and everything functioned as excepted. But now I'am developing my app and I created new Entities who are persisted in the DB and should also be auditable. I create migrations with the doctrine migration bundle to update my DB. Unfortunately the migration process creates SQL queries for dropping audit tables.

#### Current behavior
The creation of a migration with the command `php bin/console doctrine:migrations:diff` generates sql commands to drop all my current audit tables. The SQL queries for creating the audit tables of the new entities aren't unfortunately not generated but instead the tables are already created with the diff command.

#### How to reproduce

1. Create a new Entity who should be auditable
2. Run command `php bin/console doctrine:migrations:diff`
#### Expected behavior

1. No creation of tables in `php bin/console doctrine:migrations:diff` command
2. SQL Query to create the new audit tables in migration
3. No drop audit tables query

**Comment by DamienHarper** [comment]
@denis1994 Thanks for the feedback, could you please test `master` branch of `auditor`?

**Comment by denis1994** [comment]
With `master` branch of `auditor` it works as expected. Thank you!
I now also found a same issue #245 
Sorry that I didn't find it before and opened a new issue.

**Comment by DamienHarper** [comment]
@denis1994 Do you mean that you encounter #245 now that you are using `master` branch of `auditor`?
Could you please post your `dh_auditor.yaml` and `doctrine.yaml` configuration files?

**Comment by denis1994** [comment]
No with master everything works. But the #245 is the same issue as my issue.

**Comment by DamienHarper** [comment]
@denis1994 thanks for the clarification. I close this issue as you confirmed it works with `master`, feel free to reopen if needed
