### ISSUE TITLE
Different translation namespace

### ISSUE THREAD

**Issue by SanderVerkuil** [DamienHarper/auditor-bundle#253]
Currently, the translations live in the `messages` translation namespace. This could cause conflicts with existing projects that also use the same keys, but having a slightly different meaning.

Therefore I propose the idea that the translations are moved to a different namespace, but I'm not entirely sure what that namespace would be.

Wat do you think about either `audit` or `dh_audit`?

**Comment by DamienHarper** [comment]
@SanderVerkuil thanks for the feedback. I'd prefer an `auditor` namespace, would you mind submitting a relevant PR?
