### ISSUE TITLE
API Controller required

### ISSUE THREAD

**Issue by gam6itko** [DamienHarper/auditor-bundle#254]
I need to get audit data via AJAX request. Can you add ApiController?

**Comment by DamienHarper** [comment]
@gam6itko thanks for the feedback. 
As of now, you can already have a dedicated controller inside your application that makes use of `Query` object to query audit data, build JSON response etc.

What do you exactly want this `ApiController` would do/expose?

**Comment by gam6itko** [comment]
@DamienHarper I copied the ViewController and deleted the twig section for my case. Any user who needs ApiController will be forced to do the same. I think we can make this easier by making the class available out of the box.

**Comment by DamienHarper** [comment]
@gam6itko what do you mean by "deleted the twig section for my case"? do you mean you replaced the `$this->render(...)` calls with something like `$this->json(...)`?
Maybe you could submit a PR, that would be easier/clearer ;)
