### ISSUE TITLE
[Security] Make audit viewer default to disabled, or protected via a Role

### ISSUE THREAD

**Issue by timwsuqld** [DamienHarper/auditor-bundle#255]
Having the audit view (`/audit`) default to enabled could cause users of this bundle to inadvertently expose data to the public (security leak). The default config requires no authentication to access `/audit` and any objects that you are auditing will have their details viewable.

Yes, there are details of this in the documentation, but there will be plenty of people who grab this bundle to add auditing to an application, without considering the viewer portion as they don't need that yet. A good secure default would be to either disable the audit viewer by default, or require a role such as `ROLE_AUDIT_VIEWER` so that we don't default to exposing information, but also make it easy to enable the audit viewer when required.

**Comment by DamienHarper** [comment]
@timwsuqld I moved this issue to `auditor-bundle` repository as long as the viewer is an `auditor-bundle` feature.
This should be fixed now in `master` branch (viewer disabled by default).

**Comment by timwsuqld** [comment]
Thanks @DamienHarper
