### ISSUE TITLE
Clear deprecation warning

### ISSUE THREAD

**Issue by parijke** [DamienHarper/auditor-bundle#265]
Since I upgraded to SF 5.3 I see this deprecation warning:

deprecation.INFO: User Deprecated: Passing name and value is deprecated, you should pass a FilterInterface object instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Passing name and value is deprecated, you should pass a FilterInterface object instead. at /home/myproject/vendor/damienharper/auditor/src/Provider/Doctrine/Persistence/Reader/Query.php:109)"} []

**Comment by DamienHarper** [comment]
@parijke see https://github.com/DamienHarper/auditor/issues/39#issuecomment-880971991
