### ISSUE TITLE
Is there someway to use auditor-bundle with Symfony 2 

### ISSUE THREAD

**Issue by chaitanya-prac** [DamienHarper/auditor-bundle#270]
> "php": ">=7.1",
        "symfony/symfony": "2.8.*",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/assetic-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~4.0",

these are the values in the current composer.json

**Comment by DamienHarper** [comment]
@chaitanya-prac Sorry for this late reply, unfortunately `auditor` and `auditor-bundle` do not support Symfony 2.
