### ISSUE TITLE
{"error":{"message":"Unexpected \"apply\" tag (expecting closing tag for the \"macro\" tag defined near line 20).","code":0}}

### ISSUE THREAD

**Issue by cAstraea** [DamienHarper/auditor-bundle#272]
| Q                           | A
| ----------------------------| -----------------------
| `auditor-bundle` version    | 4.1.0
| PHP version                 | 7.3.30-1
| Database                    | MariaDb~

#### Summary
Getting this twig error when visiting the /audit route.

My current project setup is: 
        "damienharper/auditor-bundle": "^4.1",
        "doctrine/annotations": "1.8",
        "doctrine/cache": "1.9.1",
        "doctrine/common": "2.11",
        "doctrine/dbal": "2.9.3",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/event-manager": "1.1",
        "doctrine/instantiator": "1.3.0",
        "doctrine/orm": "2.7.*",
        "doctrine/persistence": "1.3.*",
        "symfony/symfony": "3.4.*", -> 3.4.22,
        "twig/extensions": "^1.5",
        "twig/twig": "^1.0||^2.0" --> 2.6.2

Do I need to upgrade something ? Might be able to upgrade twig but would need to test a lot of things to check if they don't break.

**Comment by cAstraea** [comment]
Update: Upgraded twig from 2.6.2 to 2.9.0 , and it works now. Hope there were no BC changes that affects.

**Comment by DamienHarper** [comment]
@cAstraea that's weird, `apply` is available since Twig 1.40 🤔 
I close the issue, feel free to reopen if needed.
