### ISSUE TITLE
[BUG] Undefined method "setFetchMode" 

### ISSUE THREAD

**Issue by TheoD02** [DamienHarper/auditor-bundle#281]
| Q                           | A
| ----------------------------| -----------------------
| `auditor-bundle` version    | 4.2.0
| PHP version                 | 8.0.9
| Database                    | SQLite
| Symfony                     | 5.3.9

#### Summary

When want to query for getting audit logs, Doctrine DBAL can't get result of SQL statement because method "setFetchMode" is undefined. When i removing, the line Audit works fine !

Location of setFetchMode is in : damienharper\auditor\src\Provider\Doctrine\Persistence\Reader\Query.php line 72

**Comment by DamienHarper** [comment]
@TheoD02 Thanks for the report. Your issue seems similar to #279 and #280: what is your `doctrine/dbal` version?

**Comment by TheoD02** [comment]
> @TheoD02 Thanks for the report. Your issue seems similar to #279 and #280: what is your `doctrine/dbal` version?

        "doctrine/annotations": "^1.0", (1.13.2)
        "doctrine/doctrine-bundle": "^2.4", (2.4.3)
        "doctrine/doctrine-migrations-bundle": "^3.2", (3.2.0)
        "doctrine/orm": "^2.10", (2.10.2)

**Comment by DamienHarper** [comment]
Okay but what about `doctrine/dbal`?
You can get current installed versions by running `composer info | grep dbal`

**Comment by TheoD02** [comment]
> Okay but what about `doctrine/dbal`?
> You can get current installed versions by running `composer info | grep dbal`

DBAL is on 3.1.3

**Comment by DamienHarper** [comment]
Right, so that's the same problem as in #279 and #280: `doctrine/dbal` 3.x is not supported and unfortunately `auditor` 1.3.0 did not prevent it to be installed. This is fixed in 1.3.1, did you follow the solution in https://github.com/DamienHarper/auditor-bundle/issues/280#issuecomment-960044053 ?

**Comment by DamienHarper** [comment]
@TheoD02 Did that fix your issue?

**Comment by TheoD02** [comment]
Hello, Yes I just tested that worked well! Thank you!
