### ISSUE TITLE
Postgre audit tables in different Postgre scheme

### ISSUE THREAD

**Issue by bezdutchek** [DamienHarper/auditor-bundle#284]
Hey, is it possible to store audit tables in different postgre scheme? We currently have all the tables in the public scheme and we would like to store the audit tables inside the audit scheme but I couldnt find anything in the docs about support of this approach. Thank you!

**Comment by DamienHarper** [comment]
@bezdutchek Sorry for that late reply, you should be able to do what you want by configuring several [entity managers for storage](https://damienharper.github.io/auditor-docs/docs/auditor-bundle/configuration/storage.html#storage-services) and a [storage mapper](https://damienharper.github.io/auditor-docs/docs/auditor-bundle/configuration/storage.html#storage-mapper).

**Comment by DamienHarper** [comment]
@bezdutchek I close this issue for now (see my previous comment). Feel free to reopen if needed.
