### ISSUE TITLE
v4 - _audit table automatically created

### ISSUE THREAD

**Issue by Herz3h** [DamienHarper/auditor-bundle#294]
| Q                    | A
| ---------------------| -----------------------
| `auditor-bundle` version    | 4.2.0
| PHP version          | 7.4.26
| Database             | MariaDB 10.4

#### Summary

`_audit` automatically created without sql query in migration

#### Current behavior

Before v4 of the bundle (not sure which version of auditor it was back then) I had every migration for new entity which has `@Auditable()` annotation, make two sql queries  (one for the new entity `my_entity` and another query for created audited table `my_entity_audit`)

But since v4 if I keep both queries (as described above), the second one that is supposed to create the `my_entity_audit` table throws and error that `my_entity_audit` already exists. This only happens with table created with v4 (not previous one), basically only new entities.

![image](https://user-images.githubusercontent.com/1900696/150311489-6511cab3-de80-4818-86c0-54d3f75bce7d.png)

Note: that between every test I drop the database.

#### How to reproduce

- Install v4 bundle
- Create an entity
- Add `@Auditable()` annotation
- Generate a migration (`php bin/console doctrine:migration:diff` and then `php bin/console doctrine:migration:migrate`). 

This migration will contain two queries, one like `CREATE TABLE my_entity...` and one for audited table `CREATE TABLE my_entity_audit...` 

 
#### Expected behavior

Right now I have to deleted the sql statement for the `_audit` table to avoid `table already exists` error which should not be the case.

**Comment by DamienHarper** [comment]
@Herz3h I haven't been able to reproduce this issue. Do you still face it or we can close this it?

**Comment by DamienHarper** [comment]
@Herz3h I close this issue for now (see my previous comment). Feel free to reopen if needed.

**Comment by Herz3h** [comment]
I still face the issue, had to remove all the `_audit` migration query statement, as it does create the `_audit` automatically without having to keep the `_audit` query statement in the generated migration.
