### ISSUE TITLE
Exception when using viewer: Attempted to call an undefined method named "fetchColumn" of class "Doctrine\DBAL\Result"

### ISSUE THREAD

**Issue by adeanzan** [DamienHarper/auditor-bundle#295]
| Q                           | A
| ----------------------------| -----------------------
| `auditor-bundle` version    | 4.2.0
| `auditor` version    | 1.3.0
| PHP version                 | 8.0.3
| Database                    | MySQL 8
| Symfony                    | 5.4.1
| Doctrine ORM           | 2.10.3
| Doctrine DBAL           | 3.2.0

#### Summary

When I attempt to use the built-in viewer to see the logs for a specific entity I get the following exception:

```
Symfony\Component\ErrorHandler\Error\UndefinedMethodError:
Attempted to call an undefined method named "fetchColumn" of class "Doctrine\DBAL\Result".

  at vendor/damienharper/auditor/src/Provider/Doctrine/Persistence/Reader/Query.php:89
  at DH\Auditor\Provider\Doctrine\Persistence\Reader\Query->count()
     (vendor/damienharper/auditor/src/Provider/Doctrine/Persistence/Reader/Reader.php:140)
  at DH\Auditor\Provider\Doctrine\Persistence\Reader\Reader->paginate()
     (vendor/damienharper/auditor-bundle/src/Controller/ViewerController.php:89)
  at DH\AuditorBundle\Controller\ViewerController->showEntityHistoryAction()
     (vendor/symfony/http-kernel/HttpKernel.php:152)
[... snip ...]
```

#### Current behavior

Exception when viewing a URL like `/audit/App-Entity-AppUser`

#### How to reproduce

1. Enable the viewer in dh_auditor.yaml (`viewer: true`)
2. Go to `/audit`
3. Next to an entity, click "View audit"

#### Expected behavior

Audit logs for the entity are shown

**Comment by DamienHarper** [comment]
Hi @adeanzan. Could you please provide your current `auditor` version?
`auditor 1.x` does not support `doctrine/dbal 3.x` but didn't prevent its installation. This has been fixed with `auditor 1.3.1`.
You should downgrade `doctrine/dbal` to a `2.x` release until `auditor 2.0` and `auditor-bundle 5.0` are available (sometime in January or February)

**Comment by adeanzan** [comment]
Thank you, I was able to resolve it by downgrading. I'm liking the bundle a lot so far and look forward to 2.0!

My auditor version is 1.3.0.

In case it's helpful to anyone else, here are the commands I used on my Symfony 5.4.2 project:

```
$ composer require doctrine/doctrine-bundle:2.4.4 --with-all-dependencies
$ composer require doctrine/dbal:2.13.1 doctrine/cache:^1.0 doctrine/orm
```

**Comment by DamienHarper** [comment]
@adeanzan I'm glad you fixed it. I close this issue, feel free to reopen it if needed.
