### ISSUE TITLE
Postgres schema

### ISSUE THREAD

**Issue by ivailo-stoianov** [DamienHarper/auditor-bundle#322]
Hello, is it possible to put all the audit tables in a separate postgres schema? Right now it just creates them in the schema of the audited entity.

**Comment by DamienHarper** [comment]
@ivailo-stoianov Sorry for this late reply, you can store audit data in a different database or schema. Please, look at the [Storage services documentation](https://damienharper.github.io/auditor-docs/docs/auditor-bundle/configuration/storage.html#storage-services).

I close this issue but feel free to reopen if needed.
