### ISSUE TITLE
Queries are not collected by Doctrine panel in Symfony profiler

### ISSUE THREAD

**Issue by ZZromanZZ** [DamienHarper/auditor-bundle#340]
| Q                    | A
| ---------------------| -----------------------
| `auditor` version    | 2.4.0
| PHP version          | 8.1.12
| Database             | MySQL 8.0.30

#### Summary

By enabling this bundle, Symfony (5.4) profiler stops collecting Doctrine queries and shows none.
![image](https://user-images.githubusercontent.com/99749/206385280-90e88fc0-5e38-4768-9a5d-247d1282e551.png)

**Comment by DamienHarper** [comment]
@ZZromanZZ thanks for the report. It should be fixed in `5.x-dev` branch. Could you please try it and keep me informed?

**Comment by ZZromanZZ** [comment]
Queries are shown in `5.x-dev` :fireworks: Thank You

**Comment by DamienHarper** [comment]
@ZZromanZZ I'll release it soon. I first need to identify why one of my tests now fails and fix it.

**Comment by DamienHarper** [comment]
@ZZromanZZ `5.2.1` is out
