### ISSUE TITLE
Compatibility with doctrine/annotations:^2.0

### ISSUE THREAD

**Issue by svenpet90** [DamienHarper/auditor-bundle#344]
[doctrine/annotations](https://github.com/doctrine/annotations) v2 was just released.

We should provide compatibility for this new version.

I'll do my best to test auditor-bundle with the new v2 this afternoon and provide a PR accordingly.

**Comment by DamienHarper** [comment]
[doctrine/annotations](https://github.com/doctrine/annotations) v2 is now supported in `5.2.3` release.
