### ISSUE TITLE
Deprecation in RoleChecker and UserProvider

### ISSUE THREAD

**Issue by Filip785** [DamienHarper/auditor-bundle#345]
Hi, upgraded security packages to 6.2 today and noticed that this package uses ``Symfony\Component\Security\Core\Security`` that is deprecated in favor of ``Symfony\Bundle\SecurityBundle\Security``. It throws following message:

``
User Deprecated: Since symfony/security-core 6.2: The "Symfony\Component\Security\Core\Security" class is deprecated, use "Symfony\Bundle\SecurityBundle\Security" instead.
``

**Comment by DamienHarper** [comment]
[auditor 3.0.0 is released](https://github.com/DamienHarper/auditor/releases/tag/3.0.0)
[auditor-bundle 6.0.0 is released](https://github.com/DamienHarper/auditor-bundle/releases/tag/6.0.0)
