### ISSUE TITLE
Example Annotation `use` Statement Shown for Auditing Configuration in Docs Undefined

### ISSUE THREAD

**Issue by AnthonyANI** [DamienHarper/auditor-bundle#361]
[The docs show](https://damienharper.github.io/auditor-docs/docs/auditor-bundle/configuration/auditing.html#example-using-annotations) a use statement `use DH\AuditorBundle\Annotation as Audit;`, but it appears there is no such Annotation available. I had to comb through past annotation issues [referencing a related pull](https://github.com/DamienHarper/auditor/pull/40#issue-944813254) to discover that it should be `use DH\Auditor\Provider\Doctrine\Auditing\Annotation as Audit;` which then allowed my schema to update and the auditor to function as expected.

Should it be the former for AuditorBundle, or the latter? I used `composer require damienharper/auditor-bundle` with Symfony Flex. Thanks.

**Comment by dmitryuk** [comment]
MR https://github.com/DamienHarper/auditor-docs/pull/12/files

**Comment by DamienHarper** [comment]
Done
