### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by dmitryuk** [DamienHarper/auditor-bundle#372]
I have tried to update to SF 6.3, but see a lot of deprecations already fixed in https://github.com/DamienHarper/auditor-bundle/pull/365/files

Please make a new release / tag of the package

**Comment by dmitryuk** [comment]
Up

**Comment by mtexeiraultra** [comment]
Up

**Comment by DamienHarper** [comment]
I currently have a very limited time and access to a computer, sorry for the delay. I will try to release a new version asap.

**Comment by dmitryuk** [comment]
@DamienHarper really need your time for us. Waiting a new  tags for `auditor` and `auditor-bundle`

**Comment by dmitryuk** [comment]
I hope the package won't be abandoned

**Comment by DamienHarper** [comment]
@dmitryuk It won't, as I previously said, I just have a very limited time till the end of the year. I'll try to make a new release asap though.

**Comment by dmitryuk** [comment]
@DamienHarper still bad news?

**Comment by craigh** [comment]
@dmitryuk I hope @DamienHarper will have time to tag a release soon too, but in the meantime you can simply use `dev-master`:

```json

{
    ...
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        ...
        "damienharper/auditor-bundle": "dev-master",
        ...
```

**Comment by dmitryuk** [comment]
@craigh I don't recommend to use `dev-master`, because you can get unverified changes, for example, when owner made major changes

**Comment by svenpet90** [comment]
up 😇

**Comment by OskarStark** [comment]
Done

**Comment by DamienHarper** [comment]
@dmitryuk [5.2.5](https://github.com/DamienHarper/auditor-bundle/releases/tag/5.2.5) is available ;)
