### ISSUE TITLE
Symfony 6.4

### ISSUE THREAD

**Issue by ganti** [DamienHarper/auditor-bundle#380]
| Q                           | A
| ----------------------------| -----------------------
| `auditor-bundle` version    | 5.2.4
| PHP version                 | 8.2.13
| Symfony version         | 6.4.1 (LTS)
| Database                    | MariaDB 10.2

#### Summary

Since updating from Symfony 6.3 to 6.4 i see the follwing error 

#### Current behavior
Error when loading /audit
`
You cannot use the "render" method if the Twig Bundle is not available. Try running "composer require symfony/twig-bundle".
`

#### How to reproduce

Update to symfony 6.4

#### Expected behavior

no error

**Comment by Riches** [comment]
This is fixed by https://github.com/DamienHarper/auditor-bundle/pull/379

**Comment by DamienHarper** [comment]
@Riches Latest release (5.2.5) includes #379. 
I close this issue as it should be fixed in 5.2.5, feel free to reopen if needed.

**Comment by ganti** [comment]
it works again, thx for fixing @OskarStark
