### ISSUE TITLE
/audit route does not after upgrade

### ISSUE THREAD

**Issue by parijke** [DamienHarper/auditor-bundle#391]
After upgrading to 6.4 the route /audit does not exist anymore. I can't seem to find where this is coming from

**Comment by parijke** [comment]
I had to add the attribute routes in the ViewController to fix this

**Comment by lussoluca** [comment]
The [AnnotatedRouteControllerLoader](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Bundle/FrameworkBundle/Routing/AnnotatedRouteControllerLoader.php) class that is used to find routes using attributes is deprecated in 6.4 and has been removed in 7.
Probably a new version of this bundle needs to be released, targeted to Symfony 7+ only.

**Comment by gassan** [comment]
> Probably a new version of this bundle needs to be released, targeted to Symfony 7+ only.

^6.4|^7.0 would be also ok.

RoutingAnnotationLoader -> RoutingAttributeLoader

**Comment by DamienHarper** [comment]
I close this issue since this should be fixed in `master` branch (PR #399).
Feel free to reopen if needed.
