### ISSUE TITLE
Additional CSS classes in twig 

### ISSUE THREAD

**Issue by ganti** [DamienHarper/auditor-bundle#392]
@DamienHarper 
Our app runs in darkmode. I tried to customize the layout, but not all worked well.  Therefore it would be helpful to gave additional css classes for entries and transaction, would you accept a PR with additional classes in the layouts?

**Comment by DamienHarper** [comment]
@ganti Sure, your PR would be welcome

**Comment by ganti** [comment]
@DamienHarper thanks to you, though it would be nice, if you create a release, so i can use it as a stable version.
