### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by dmitryuk** [DamienHarper/auditor-bundle#401]
@DamienHarper I need Symfony 7 support
Please make a new release

**Comment by Gonzalo1987** [comment]
Same here 😄 <3

**Comment by OskarStark** [comment]
That would be really helpful!

**Comment by dmitryuk** [comment]
@DamienHarper please make a minute for a release

**Comment by putzwasser** [comment]
@DamienHarper +1 Would be highly appreciated

**Comment by dmitryuk** [comment]
@DamienHarper please wake up

**Comment by garciac12** [comment]
@DamienHarper if you need help, please tell us, we need a version for Symofny 7 !!!

**Comment by MarkDaleman** [comment]
Is this project maintained or is @DamienHarper gone?

**Comment by martinbertinat** [comment]
We are going to have to either create or find a fork of the project.

**Comment by DamienHarper** [comment]
> Is this project maintained or is @DamienHarper gone?

It still is, I'm not completely gone, I just didn't have any time left these past monthes.
A new version will be released anytime soon

**Comment by DamienHarper** [comment]
Hi @yivi, this files are in `auditor` test suite.
Try `composer reinstall damienharper/auditor --prefer-install=source` and run your tests agains

**Comment by yivi** [comment]
Awesome! Tests seems to be passing fine on PHP 8.3.9.

Is there anything I could do to give a hand with a release? Add or concentrate on a specific area for testing?

**Comment by dmitryuk** [comment]
@DamienHarper please take 10 minutes to make a new release

**Comment by yivi** [comment]
@dmitryuk if you only need the maintainer to "take 10 minutes", you could also take 10 minutes to create a fork, tag a release, and use that. Or even pull from dev-master.

If that's not actually useful to you, then you want more than 10 minutes work. And one should try to be more respectful when asking someone for free work.

While I understand and share the frustration, we are not owed work by the author of a project.

**Comment by dmitryuk** [comment]
Bundle is abandoned I close an issue and make an own fork

**Comment by DamienHarper** [comment]
@dmitryuk bundle is not abandoned but feel free to make your own fork if you want

**Comment by OskarStark** [comment]
you can also bin the current commit in you composer.json 🤷‍♂️ this way you are sure you get nothing new, which is not release

**Comment by ThomasBerends** [comment]
@DamienHarper 
Has the current 5.x branch been tested with Symfony 7? Are there any problems with adding Symfony 7 + Doctrine/Orm 3 support to the composer.json and adding that as a new 5.x release?

If there's compatibility issues, I'm sure we can help fix those.

**Comment by DamienHarper** [comment]
I hear you guys, I promise I will release it shortly

**Comment by DamienHarper** [comment]
`doctrine/orm` 3.x support is coming soon

**Comment by DamienHarper** [comment]
[auditor 3.0.0 is released](https://github.com/DamienHarper/auditor/releases/tag/3.0.0)
[auditor-bundle 6.0.0 is released](https://github.com/DamienHarper/auditor-bundle/releases/tag/6.0.0)

**Comment by ThomasBerends** [comment]
Thank you a lot!
