### ISSUE TITLE
Symfony 7 installation error

### ISSUE THREAD

**Issue by iAdil** [DamienHarper/auditor-bundle#409]
Can you please allow symfony/asset 7 version?

**Comment by heurisko** [comment]
please please please symfony 7 🙏🏿

**Comment by rsereir** [comment]
Yes, up for Symfony 7 too, please 🙏

**Comment by dmitryuk** [comment]
#401

**Comment by DamienHarper** [comment]
[auditor 3.0.0 is released](https://github.com/DamienHarper/auditor/releases/tag/3.0.0)
[auditor-bundle 6.0.0 is released](https://github.com/DamienHarper/auditor-bundle/releases/tag/6.0.0)
