### ISSUE TITLE
symfony 6.4 support

### ISSUE THREAD

**Issue by dvdknaap** [DamienHarper/auditor-bundle#422]
Could you please update your composer.json so it will fully support symfony 6.4 ?

When i want to install it, i am getting the following error:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - damienharper/auditor-bundle[1.0.0, ..., 1.2.1] require doctrine/orm ^2.5 -> found doctrine/orm[v2.5.0, ..., 2.19.6] but it conflicts with your root composer.json require (^3.0).
    - damienharper/auditor-bundle[1.2.2, ..., 1.6.0, 2.0.0, ..., 2.5.0] require symfony/security-bundle ^3.4 || ^4.0 -> found symfony/security-bundle[v3.4.0, ..., v3.4.48, v4.0.0, ..., v4.4.50] but it conflicts with your root composer.json require (6.4.*).
    - damienharper/auditor-bundle 3.0.0 requires symfony/event-dispatcher ^3.4 || ^4.0 -> found symfony/event-dispatcher[v3.4.0, ..., v3.4.47, v4.0.0, ..., v4.4.44] but these were not loaded, likely because it conflicts with another require.
    - damienharper/auditor-bundle[3.1.0, ..., 3.2.3, 5.2.3, ..., 5.2.5] require doctrine/orm ^2.7 -> found doctrine/orm[v2.7.0, ..., 2.19.6] but it conflicts with your root composer.json require (^3.0).
    - damienharper/auditor-bundle[3.3.0, ..., 3.4.2, 4.0.1, ..., 4.2.0, 5.0.0, ..., 5.2.2] require doctrine/annotations ^1.8 -> found doctrine/annotations[v1.8.0, ..., 1.14.3] but it conflicts with your root composer.json require (^2.0).
    - damienharper/auditor-bundle 4.0.0 requires damienharper/auditor dev-master -> found damienharper/auditor[dev-master, 3.x-dev (alias of dev-master)] but it does not match your minimum-stability.
    - Root composer.json requires damienharper/auditor-bundle * -> satisfiable by damienharper/auditor-bundle[1.0.0, ..., 1.6.0, 2.0.0, ..., 2.5.0, 3.0.0, ..., 3.4.2, 4.0.0, ..., 4.2.0, 5.0.0, ..., 5.2.5].

**Comment by Gonzalo1987** [comment]
auditor-bundle support fully symfony 6.4, that seems you are having problems when using doctrine/orm 3.0

You can see it in the line where is indicated the conflict to use the last version of auditor bundle (5.2.5):
- damienharper/auditor-bundle[3.1.0, ..., 3.2.3, 5.2.3, ..., 5.2.5] require doctrine/orm ^2.7 -> found doctrine/orm[v2.7.0, ..., 2.19.6] but it conflicts with your root composer.json require (^3.0).

Symfony 6.4 doesn't requires doctrine/orm 3.0

**Comment by mvhirsch** [comment]
Which version of auditor-bundle do you use? Please post your composer.json requirements here, so others better understand the problem and be able to help you.

> Could you please update your composer.json so it will fully support symfony 6.4 ?

Latest 5.2.5 does support Symfony 6.4.

https://github.com/DamienHarper/auditor-bundle/blob/a03c399b3703fa5be1e69f166aa71f2adffdc43a/composer.json#L20-L26


But looking at the first problem:

>  - damienharper/auditor-bundle[1.0.0, ..., 1.2.1] require doctrine/orm ^2.5 -> found doctrine/orm[v2.5.0, ..., 2.19.6] but it conflicts with your root composer.json require (^3.0).

it looks like your composer.json requires `doctrine/orm` v3, which is currently _not_ supported by auditor-bundle:

https://github.com/DamienHarper/auditor-bundle/blob/a03c399b3703fa5be1e69f166aa71f2adffdc43a/composer.json#L19

Of course, this is the very same information @Gonzalo1987 already gave you. But you have some options left:

You could downgrade `doctrine/orm` to ^2.7, but I guess that's not an option?

However, this bundle needs support for `doctrine/orm` v3. Are you open for a working on it and create a merge request?

**Comment by DamienHarper** [comment]
[auditor 3.0.0 is released](https://github.com/DamienHarper/auditor/releases/tag/3.0.0)
[auditor-bundle 6.0.0 is released](https://github.com/DamienHarper/auditor-bundle/releases/tag/6.0.0)
