### ISSUE TITLE
Why dropping PHP 8.1 support on v6 release?

### ISSUE THREAD

**Issue by mvhirsch** [DamienHarper/auditor-bundle#434]
Why did this project drop PHP 8.1 support on v6 release 8295c1bbceb9aec7038d77f2da06abe483d565fc? PHP 8.1 still [receives security updates](https://endoflife.date/php) and is actively maintained. 

I'm using a Symfony 6.4 LTS on a PHP 8.1 platform, but I'm not able to install this precious update. 

Are you using any PHP 8.2 related new features? Would it be possible to downgrade this?

**Comment by DamienHarper** [comment]
Hi @mvhirsch, Symfony 7 support implied PHP >= 8.2

**Comment by mvhirsch** [comment]
> Symfony 7 support implies PHP >= 8.2 (https://symfony.com/releases/7.0)

This doesn't force anybody to upgrade the minimum version of any dependency in a maintained package like this. 

>  Also, some PHP 8.2 features are used both in auditor and auditor-bundle.

This does.
